[package]
name = "seonkim1003/bella-game"
description = "Roblox experience scaffolded with Rojo, Rokit, and Luau"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
